spring:
    application:
        name: message
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                query.substitutions: true 1, false 0
                max_fetch_depth: 2
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                connection.zeroDateTimeBehavior: convertToNull
                enable_lazy_load_no_trans: false
                globally_quoted_identifiers: true
    kafka:
        bootstrap-servers: ${KAFKA:127.0.0.1}:9092
        consumer:
            group-id: platform-message-service
            auto-offset-reset: latest
