spring:
  application:
    name: monitor
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        query.substitutions: true 1, false 0
        max_fetch_depth: 2
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        connection.zeroDateTimeBehavior: convertToNull
        enable_lazy_load_no_trans: false
        globally_quoted_identifiers: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
      prefer-ip-address: false


feign:
  client:
    config:
      default:
        connect-timeout: 200
        read-timeout: 5000


