server:
    port: 8803

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/hawk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    redis:
        host: localhost

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
        registry-fetch-interval-seconds: 5
hawk:
    container:
        default-instance-namespace: default
        domain-host: hawk.cn
        build-namespace: build
        app-image-prefix: "registry.cn-beijing.aliyuncs.com/9fbank/"
        gateway-url: "localhost:8001"
        pvc-log: true



